include .config
include script/Makefile.toolchain.$(TOOLCHAIN)
include $(PROJECT_BASE)/objects.mk

ifeq ($(TOOLCHAIN),armclang)
    ARFLAGS	:=-cr
else
    ARFLAGS	:=cr
endif

all: $(TARGET)

%.a: $(obj)
	@echo "[AR]        $@"
	$(Q)$(AR) $(ARFLAGS) $@ $(obj)
